<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Kegiatan_model extends CI_Model
{

    public $table = 'kegiatan';
    public $id = 'kegiatan_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->load->library('upload');
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kegiatan_id', $q);
        $this->db->or_like('kegiatan_gambar', $q);
        $this->db->or_like('kegiatan_deskripsi', $q);
        $this->db->or_like('kegiatan_waktu', $q);
        $this->db->or_like('admin_username', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('kegiatan_id', $q);
	$this->db->or_like('kegiatan_gambar', $q);
	$this->db->or_like('kegiatan_deskripsi', $q);
	$this->db->or_like('kegiatan_waktu', $q);
	$this->db->or_like('admin_username', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        if ($this->_rules() != FALSE) {
            $config['upload_path'] = './uploads/';
            $config['allowed_types'] = 'gif|jpg|png';
            $config['max_size']     = '2048';
            $this->upload->initialize($config);

            if (! $this->upload->do_upload('kegiatan_gambar')) {
                return array('error' => $this->upload->display_errors());
            } else {
                $insert = array(
                    'kegiatan_gambar'      => $data['kegiatan_gambar'],
                    'kegiatan_judul'       => $data['kegiatan_judul'],
                    'kegiatan_deskripsi'   => $data['kegiatan_deskripsi'],
                    'kegiatan_waktu'       => $data['kegiatan_waktu'],
                    'kategori_kegiatan_id' => $data['kategori_kegiatan_id'],
                    'admin_username'       => $this->session->username
                );
                $this->db->insert($this->table, $insert);
            }
        }
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    private function _rules() {
        $this->form_validation->set_rules('kegiatan_judul', 'judul kegiatan', 'trim|required');
        $this->form_validation->set_rules('kegiatan_deskripsi', 'deskripsi kegiatan', 'trim|required');
        $this->form_validation->set_rules('kegiatan_waktu', 'waktu kegiatan', 'trim|required');
        $this->form_validation->set_rules('kategori_kegiatan_id', 'Kategori', 'trim|required');
        $this->form_validation->set_error_delimiters('<small class="text-danger">', '</small>');
        return $this->form_validation->run();
    }
}

/* End of file Kegiatan_model.php */
/* Location: ./application/models/Kegiatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-26 01:27:52 */
/* http://harviacode.com */